### ISSUE TITLE
Add Docker examples

### ISSUE THREAD

**Issue by ssbostan** [ssbostan/terraform-awesome#1]
Hi contributors,

We have to develop several examples for the Docker provider to complete this milestone.

Please comment on this issue and tell us which do you choose to work on it.

The following are our primary goals:

- [x] 01 pull an image and deploy a container `easy-simple-image-container`
- [x] 02 build image simple code `easy-simple-build-image`
- [x] 03 build image with some build args `easy-build-image-build-args`
- [x] 04 pull from private registry and deploy the container `moderate-pull-private-image-container`
- [x] 05 pull new layers if new version is available on the registry `moderate-pull-new-image-layers-container`
- [x] 06 create local volume `easy-simple-volume-local`
- [x] 07 create nfs volume `moderate-volume-nfs-storage`
- [x] 08 import an existing volume to terraform `moderate-import-existing-volume`
- [x] 09 install new docker plugin `easy-install-docker-plugin`
- [x] 10 import an existing plugin to terraform `moderate-import-existing-docker-plugin`
- [x] 11 create a new network with default driver `easy-simple-network-default-driver`
- [x] 12 create a new bridge network with custom IP address `moderate-custom-network-bridge-driver`
- [x] 13 import an existing network to terraform `moderate-import-existing-network`
- [x] 14 create a new container with limited CPU and RAM resources `easy-container-limit-cpu-ram`
- [x] 15 create a new container with some env variables from terraform variables `easy-container-env-variables`
- [x] 16 create a new container and upload data to it `easy-container-upload-data`
- [x] 17 create a new container and attach a custom network to it `easy-container-custom-network`
- [x] 18 create a new container and publish its ports `easy-container-publish-ports`
- [x] 19 create a new container and add some new kernel parameters `easy-container-kernel-parameter`
- [x] 20 create a new container and add some capabilities `easy-container-linux-capabilities`
- [x] 21 create a new container and mount some host directories to it `easy-container-mount-host-dir`
- [x] 22 create a new container and mount docker volume to it `easy-container-mount-volume`
- [x] 23 import an existing container to terraform `moderate-import-existing-container`
- [x] 24 create a new container with some ulimit options `easy-container-ulimit-options`
- [x] 25 create a new container with some labels `easy-container-with-labels`
- [x] 26 create a new container with some /etc/hosts entries `easy-container-add-host`
- [x] 27 create two containers and link them together `easy-container-link-together`
- [x] 28 create a new container with healthcheck `easy-container-with-healthcheck`
- [x] 29 create a new container in privileged mode `easy-container-privileged-mode`
- [x] 30 create a new container and customize its namespaces `easy-container-custom-namespace`
- [x] 31 create nginx container with all needed options and publish its port `easy-nginx-simple-container`
- [x] 32 create nginx container with all needed options, publish port and mount nginx root dir `easy-nginx-with-root-dir`
- [x] 33 create nginx container with self-signed SSL/TLS with terraform `moderate-nginx-https-self-signed-certificate`
- [x] 34 create nginx container with letsencrypt SSL/TLS with terraform `moderate-nginx-https-letsencrypt-certificate`
- [x] 35 create redis container with all needed options and tmpfs `easy-redis-tmpfs-data`
- [x] 36 create redis container with custom config file and publish its port `easy-redis-config-mount`
- [x] 37 create MySQL container with all need options and publish it `easy-mysql-simple-container`
- [x] 38 create MySQL container with some SQL file for first time initialization `moderate-mysql-init-sql-data`
- [x] 39 create MySQL and PhpMyAdmin containers and config them `moderate-mysql-phpmyadmin-stack`
- [x] 40 create wordpress stack with wordpress and MySQL and config them `moderate-wordpress-stack-production`

Feel free and add other docker related codes.

Thanks.

**Comment by ssbostan** [comment]
I will work on 01 pull an image and deploy a container `easy-simple-image-container`

**Comment by ravanbod** [comment]
I will work on 02 build image simple code `easy-simple-build-image`

**Comment by saeedya** [comment]
03 build image with some build args easy-build-image-build-args

**Comment by saeedya** [comment]
I will work on 02 build image simple code easy-simple-build-image

**Comment by x004A** [comment]
I will work on 06 `easy-simple-volume-local`

**Comment by saeedya** [comment]
I will work on 06 easy-simple-volume-local

**Comment by mrunix1998** [comment]
I will work on  14 create a new container with limited CPU and RAM resources `easy-container-limit-cpu-ram`

**Comment by ssbostan** [comment]
I will work on 33 create nginx container with self-signed SSL/TLS with terraform `moderate-nginx-https-self-signed-certificate` it should be ready today.

**Comment by Sms-Rk** [comment]
i will work on 05 pull new layers if new version is available on the registry `moderate-pull-new-image-layers-container`

**Comment by mehran-torkaman** [comment]
i will work on 18 create a new container and publish its ports easy-container-publish-ports

**Comment by mehran-torkaman** [comment]
i will work on 27 create two containers and link them together easy-container-link-together

**Comment by mehran-torkaman** [comment]
i will work on 37 create MySQL container with all need options and publish it easy-mysql-simple-container

**Comment by x004A** [comment]
i will work on 35 create redis container with all needed options and `tmpfs easy-redis-tmpfs-data`

**Comment by ehsantux** [comment]
I will work on 28 create a new container with healthcheck easy-container-with-healthcheck

**Comment by Sms-Rk** [comment]
i will work on 37 create MySQL container with all need options and publish it `easy-mysql-simple-container`

**Comment by mi-alkhamis** [comment]
I will work on  11 create a new network with default driver `easy-simple-network-default-driver`

**Comment by saeedhosseini21** [comment]
I will work on 39 create MySQL and PhpMyAdmin containers and config them `moderate-mysql-phpmyadmin-stack`

**Comment by Sms-Rk** [comment]
i will work on 40 create wordpress stack with wordpress and MySQL and config them `moderate-wordpress-stack-production`

**Comment by saeedhosseini21** [comment]
I will work on 36 create redis container with custom config file and publish its port `easy-redis-config-mount`

**Comment by ehsantux** [comment]
I will work on 31 create nginx container with all needed options and publish its port `easy-nginx-simple-container`

**Comment by mi-alkhamis** [comment]
I will work on  23 import an existing container to terraform `moderate-import-existing-container`

**Comment by mi-alkhamis** [comment]
I will work on  26 create a new container with some /etc/hosts entries `easy-container-add-host`

**Comment by mi-alkhamis** [comment]
I will work on  40 create wordpress stack with wordpress and MySQL and config them `moderate-wordpress-stack-production`

**Comment by majidroodi** [comment]
I will work on 08 import an existing volume to terraform moderate-import-existing-volume

**Comment by majid1400** [comment]
I will work on 15 create a new container with some env variables from terraform variables `easy-container-env-variables`

**Comment by mrunix1998** [comment]
I will work on 24 create a new container with some ulimit options `easy-container-ulimit-options`

**Comment by mrunix1998** [comment]
I will work on 34 create nginx container with letsencrypt SSL/TLS with terraform `moderate-nginx-https-letsencrypt-certificate`

**Comment by baniasadi-m** [comment]
I will work on  29 create a new container in privileged mode `easy-container-privileged-mode`

**Comment by amirnoshian** [comment]
i will work on 18 create a new container and publish its ports easy-container-publish-ports

**Comment by imohsen7** [comment]
i will work on 04 pull from private registry and deploy the container `moderate-pull-private-image-container`

**Comment by saeedhosseini21** [comment]
I will work on 12 create a new bridge network with custom IP address `moderate-custom-network-bridge-driver`

**Comment by mi-alkhamis** [comment]
I will work on  38 create MySQL container with some SQL file for first time initialization `moderate-mysql-init-sql-data`

**Comment by peymansafiri** [comment]
I will work on 32 create nginx container with all needed options, publish port and mount nginx root dir easy-nginx-with-root-dir

**Comment by kyarmitaj** [comment]
I will work on 21 create a new container and mount some host directories to it easy-container-mount-host-dir

**Comment by ehsantux** [comment]
I will work on 17  create a new container and attach a custom network to it `easy-container-custom-network`

**Comment by imohsen7** [comment]
I will work on 19 create a new container and add some new kernel parameters `easy-container-kernel-parameter`

**Comment by imohsen7** [comment]
I will work on  30 create a new container and customize its namespaces `easy-container-custom-namespace`

**Comment by imohsen7** [comment]
I will work on 20 create a new container and add some capabilities `easy-container-linux-capabilities`

**Comment by moh3nsh** [comment]
I will work on 15 create a new container with some env variables from terraform variables easy-container-env-variables

**Comment by nimatbt** [comment]
I will work on 20 create a new container and add some capabilities `easy-container-linux-capabilities`

**Comment by mamirpanah** [comment]
I will work on 38 create MySQL container with some SQL file for first time initialization moderate-mysql-init-sql-data

- [x] OK

**Comment by saeedya** [comment]
I will work on  10 import an existing plugin to terraform moderate-import-existing-docker-plugin.

**Comment by mamirpanah** [comment]
I will work on 40 create wordpress stack with wordpress and MySQL and config them moderate-wordpress-stack-production

- [x] OK

**Comment by RArmandeh** [comment]
will work on 15 create a new container with some env variables from terraform variables 'easy-container-env-variables'

**Comment by ssbostan** [comment]
We will release the first version soon. Thank you all.
